sample_rate: 44100

# Maximum number of consine waves to use for each frame
cosine_waves: 10

# Fast Fourier Transformation parameter n_fft
n_fft: 1024

# FFT window size, n_fft is usually recommended
window_len: 512

# FFT hop length, n_fft/4 is usually recommended
hop_len: 512

# Frequency tolerance used in frequency tracker
freq_tolerance: 0.01

# Frame length, 2*hop_len is usually recommended
frame_len: 1024